// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Task struct {
	ID          int64
	UserID      int64
	Description string
	Status      bool
	CreatedAt   sql.NullTime
	Foreign     interface{}
}

type User struct {
	ID         int64
	AccessCode string
	CreatedAt  sql.NullTime
}
