// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Task struct {
	ID          int64
	Description string
	Status      bool
	CreatedAt   sql.NullTime
}
